
class Autogenerated {
  List<Vehicles> vehicles;

  Autogenerated({this.vehicles});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['vehicles'] != null) {
      vehicles = <Vehicles>[];
      json['vehicles'].forEach((v) { vehicles.add(new Vehicles.fromJson(v)); });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.vehicles != null) {
      data['vehicles'] = this.vehicles.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
class Vehicles {
  int id;
  String name;
  String logo;
  String basePrice;
  String baseDistance;
  int status;
  String additionalDistancePricing;
  String appTax;
  String default_vehicle;
  String createdAt;
  String updatedAt;

  Vehicles({this.id, this.name, this.logo, this.basePrice,
  this.baseDistance, this.status, this.additionalDistancePricing,
    this.appTax, this.default_vehicle, this.createdAt, this.updatedAt});

Vehicles.fromJson(Map<String, dynamic> json) {
id = json['id'];
name = json['name'];
logo = json['logo'];
basePrice = json['base_price'];
baseDistance = json['base_distance'];
status = json['status'];
additionalDistancePricing = json['additional_distance_pricing'];
appTax = json['app_tax'];
default_vehicle = json['default_vehicle'];
createdAt = json['created_at'];
updatedAt = json['updated_at'];
}

Map<String, dynamic> toJson() {
final Map<String, dynamic> data = new Map<String, dynamic>();
data['id'] = this.id;
data['name'] = this.name;
data['logo'] = this.logo;
data['base_price'] = this.basePrice;
data['base_distance'] = this.baseDistance;
data['status'] = this.status;
data['additional_distance_pricing'] = this.additionalDistancePricing;
data['app_tax'] = this.appTax;
data['default'] = this.default_vehicle;
data['created_at'] = this.createdAt;
data['updated_at'] = this.updatedAt;
return data;
}
}
