name: sandav
description: A new Flutter application.
publish_to: "none" #
version: 1.9.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity: ^3.0.6
  flutter_lints: ^2.0.0
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.5.3+1
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^7.3.0
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2
  flutter_typeahead: ^4.0.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  universal_html: ^2.0.8
  universal_ui: ^0.0.8

  loading_indicator: ^3.0.2
  file_picker: ^3.0.0
  dio: ^4.0.0


  flutter_inappwebview: ^5.4.3+7
  flutter_widget_from_html_core: ^0.8.5+3
  url_launcher: ^6.0.17
  http: ^0.13.4
  iconsax: ^0.0.8
  permission_handler: ^10.2.0
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  cached_network_image: ^3.2.1
  #  google_sign_in: ^5.2.1
  #  flutter_facebook_auth: ^3.5.7
  photo_view: ^0.14.0
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.4
  custom_map_markers: ^0.0.2+1
  image_compression_flutter: ^1.0.2
  fwfh_text_style: ^2.22.8+1
  auto_size_text: ^3.0.0

  cupertino_icons: ^1.0.5
  nb_utils: ^4.6.21
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1
  flutter_mobx: ^2.0.6+5
  googleapis: ^9.2.0
  google_sign_in: ^5.4.2
  googleapis_auth: ^1.3.1
  intl: ^0.17.0
  flutter_rating_bar: 4.0.1
  #url_launcher: 6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  build_runner: ^2.2.1
  dart_code_metrics: ^5.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo_launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/language/
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900